configuration:
  Name: EmotionChattingMachine
  decoder:
    attn_num_units: 128
    cell_type: LSTM
    emo_cat_units: 32
    emo_int_units: 64
    num_emotions: 4
    num_layers: 2
    num_units: 256
    state_pass: true
    wrapper: ECM
  embeddings:
    embed_size: 128
    vocab_size: 1000
  encoder:
    bidirectional: true
    cell_type: LSTM
    num_layers: 2
    num_units: 256
  inference:
    beam_size: 5
    choice_path: ./choice_pred.txt
    infer_batch_size: 15
    infer_category_file: ./example/dev_category.txt
    infer_source_file: ./example/dev_source.txt
    infer_source_max_length: 25
    max_length: 20
    output_path: ./prediction.txt
    type: beam_search
  training:
    batch_size: 64
    checkpoint_every: 1000
    dev_category_file: ./example/dev_category.txt
    dev_choice_file: ./example/dev_choice.txt
    dev_source_file: ./example/dev_source.txt
    dev_target_file: ./example/dev_target.txt
    gpu_fraction: 0.05
    l2_regularize: null
    learning_rate: 0.001
    logdir: ./log_ecm/
    loss_fig: ./ECM_training_loss_over_time
    max_checkpoints: 10000
    perplexity_fig: ./ECM_perplexity_over_time
    print_every: 20
    restore_from: ./log_ecm/
    source_max_length: 25
    target_max_length: 25
    train_category_file: ./example/train_category.txt
    train_choice_file: ./example/train_choice.txt
    train_source_file: ./example/train_source.txt
    train_steps: 5000
    train_target_file: ./example/train_target.txt
